services:
  - name: laravel-app
    type: web
    env: docker
    repo: https://github.com/Bramos20/job_finder
    region: oregon
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:1tO87SQlDLqC71m2E9F1tgUMz1kNDZ7XuDYI1yu4a5U=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_DATABASE
        value: jobsearch
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 
